# Plugins
plugins: [jekyll-paginate, jekyll-gist, jekyll-pandoc]

# Dependencies
markdown:         Pandoc
highlighter:      rouge

pandoc:
  extensions:
    - bibliography: _bibliography/references.bib
    - csl: _bibliography/nature-no-et-al
    - filter: pandoc-fignos

# Permalinks
permalink:        pretty

# Setup
title:            Phillip J. Wolfram
tagline:          'Computational fluid science and engineering'
description:      'Computational fluid science and engineering '
url:              http://pwolfram.github.io
baseurl:          /

author:
  name:           'Phillip J. Wolfram'
  url:            https://pwolfram.github.io

paginate:         5
paginate_path: "page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pwolfram/pwolfram.github.io

profile:          https://github.com/pwolfram/

exclude: [Rakefile]
